### ISSUE TITLE
右键菜单里没有编译选项的问题

### ISSUE THREAD

**Issue by wangnengquan** [zuozishi/C51-Extension-for-VScode#1]
昨晚看了一下，是因为后缀名为大C造成的。小c就没问题。
虽然安装完微软的c/c++仍然提示有错误，但是可以编译。

**Comment by zuozishi** [comment]
.C 文件的问题已经解决并提交了更新。
语法提示错误为C51特性与标准C的差异。本人由于对vscode语言支持类型的插件了解过浅还没有能力开发出语法支持插件，不过目前正在对vscode的开发正在深入了解。

**Comment by wangnengquan** [comment]
VScode的商店里面没有更新吗，旧版本里，又发现一个新问题，发了一个新的Issues，不知道是不是操作问题。
