### ISSUE TITLE
C51关键字支持问题

### ISSUE THREAD

**Issue by yuxiaoyuan0406** [zuozishi/C51-Extension-for-VScode#3]
编辑过程中对于C51关键字和特殊语法还是会报错, 比如
`
sbit led = P2 ^ 0;    // 这里sbit会报错, P2的定义sfr也会报错
`
或者中断函数声明时使用的关键字interrupt和using, 以及code等关键字

**Comment by Naskita** [comment]
ctrl+shift+x添加C/C++扩展，然后ctrl+shift+P进入命令C/C++: Edit configurations
将其内容改为：
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
            "${workspaceRoot}",
            "${workspaceRoot}/code",
            "${workspaceRoot}/code/driver",
            "${workspaceRoot}/code/common"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "sbit=char",
                "sfr=char",
                "bit=char",
                "FOSC_160000",
                "interrupt 2 ="
            ],
            "windowsSdkVersion": "10.0.17763.0",
            "browse": {
                "path": [
                "${env.KEIL_C51_INC}",
                "${workspaceRoot}",
                "${workspaceRoot}/code",
                "${workspaceRoot}/code/driver",
                "${workspaceRoot}/code/common"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
                },
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64"
        }
    ],
    "version": 4
}
---------
其中"compilerPath"如不需要可以去掉，有哪个关键字报错就在"defines"里添加即可

**Comment by zuozishi** [comment]
关键词报错问题在插件中暂无解决方案，但是不影响编译，下一个更新已实现include的Go to definition
