### ISSUE TITLE
一个小建议：优化链接和编译

### ISSUE THREAD

**Issue by Naskita** [zuozishi/C51-Extension-for-VScode#4]
建议使用以下编译命令替代原编译命令，REMOVEUNUSED关键字可去除没有使用的语句，节省空间，另外这种编译方式也可以避免代码ROM大小占用超过2k无法通过编译的问题（即代码ROM大小为64K），如果需要更多空间，或者自定义寻址，需参考keil\c51\hlp目录下的LX51.chm相关内容。
`cmd.sendText("\""+binDir+"\\C51.exe"+"\" "+"\""+filePath+".c\"",true);
cmd.sendText("\""+binDir+"\\LX51.exe"+"\" "+"\""+filePath+".OBJ to \""+filePath+".abs REMOVEUNUSED \"",true);
cmd.sendText("\""+binDir+"\\OHx51.exe"+"\" "+"\""+filePath+".abs\"",true);`

**Comment by zuozishi** [comment]
3Q，已添加到下一个版本的代码，还有一些新功能
